### PR TITLE
Misc changes

### PR DESCRIPTION
**Pull request by im-denisenko**
Hello.

I made some improvements, so now your plugin looks like real usable plugin. For full list of changes please read commit messages.

If you will accept PR, please make a new release with version 0.0.1, and [register your package](http://bower.io/docs/creating-packages/#register) in bower registry. Something like that:

``` bash
git clone git@github.com:Saluev/bootstrap-file-dialog.git
cd bootstrap-file-dialog
git tag -a 'v0.0.1' -m 'Release v0.0.1'
git push origin --tags
sudo apt-get install nodejs -y
sudo npm install bower -g
bower register bootstrap-file-dialog git://github.com/Saluev/bootstrap-file-dialog.git
```

### CODE REVIEW

**Comment by Saluev** [comment]
Wow. Thanks a lot!

**Comment by im-denisenko** [comment]
You're welcome! 
Would you like similar PR [here](https://github.com/Saluev/flexed)?

**Comment by Saluev** [comment]
Don't think so. That project is in its very beginning currently.

**Comment by im-denisenko** [comment]
> Last commit 6 months ago

Yeah, very-very :) Ok then

**Pull request merged**
